### ISSUE TITLE
KUBEIP_NODEPOOL prefix/wildcard

### ISSUE THREAD

**Issue by gojanpaolo** [doitintl/kubeip#105]
Hello! We're going to create our node pool using terraform's `google_container_node_pool` with a `name_prefix = "default-pool-"`. This means the names of our node pools will be something like `default-pool-12345` where `12345` will be randomly generated. Is there any way to pass in a pattern/regex/wildcard to kubeip such that it will assign static ip addresses to a node pool that matches that pattern (e.g. `default-pool-*`)? Thanks!

**Comment by alexei-led** [comment]
no plans to implement
switch to KubeIP v2
