### ISSUE TITLE
KUBEIP_COPYLABELS not applying labels

### ISSUE THREAD

**Issue by f0o** [doitintl/kubeip#106]
**Describe the bug**
Using the sample from the README and KUBEIP_COPYLABELS=true as well as KUBEIP_CLEARLABELS=true no tag "platform_whitelisted" is created on the node, only "kubip_assigned" is created.

**To Reproduce**
1. Tag your IP as per documentation
2. Deploy DS/CM with KUBEIP_COPYLABELS=true
3. Observe missing tag

**Expected behavior**
Tag to exist on nodes

**Screenshots**
./.

**Desktop (please complete the following information):**
 - GKE v1.27.3-gke.100

**Smartphone (please complete the following information):**
???

**Additional context**

**Comment by f0o** [comment]
Looking at https://github.com/doitintl/kubeip/blob/master/pkg/utils/k8sutil.go

it seems from the logs that https://github.com/doitintl/kubeip/blob/master/pkg/utils/k8sutil.go#L146 is never entered because the log-line at https://github.com/doitintl/kubeip/blob/master/pkg/utils/k8sutil.go#L167 or https://github.com/doitintl/kubeip/blob/master/pkg/utils/k8sutil.go#L169 arent printed at all.

The only log line I see is the initial one from https://github.com/doitintl/kubeip/blob/master/pkg/utils/k8sutil.go#L142

Does https://github.com/doitintl/kubeip/blob/master/pkg/config/config.go#L83 actually work correctly when set through env?

**Comment by f0o** [comment]
After removing the ENV vars to use the defaults there is still no tags; I'm a bit at a loss here now...

Did the computeService change to not include Labels in it's reply now? Am I missing something entirely else (IAM?)?

Am I just blind?

**Comment by alexei-led** [comment]
Fixed

**Comment by f0o** [comment]
@alexei-led not sure about that; Now I'm having this fun issue:
Tagging node gke-b8be1266-qb5p as 0.0.0.0 with tags {\"kubip_assigned\":\"0-0-0-0\"} " function=tagNode pkg=kubeip"
