### ISSUE TITLE
Implementation in on-premises/Bare metal clusters.

### ISSUE THREAD

**Issue by jefersonlopes-br** [doitintl/kubeip#116]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**

Possibility of deployment on a bare metal cluster such as a private cluster or used together with K3s or MicroK8s.

This implementation would be for cases where solutions in which using a Load Balancer at a service level such as MetalLB does not bring all the expected resolution.

**Describe alternatives you've considered**

Some applications require a static IP to function correctly in a HomeLab and when the Pod ends, restart it, due to the image version update of a deployment manifest, the application such as Freeipa does not go up due to the IP validation of the " host" and certificates for the domain at Pod level. Help us, mere mortals who just want to carry on with their personal data in our home laboratories... =) please. Thank you.

**Comment by alexei-led** [comment]
no plans to support bare-metal private K8s
