### ISSUE TITLE
Kubeip using a lot of CPU

### ISSUE THREAD

**Issue by aimbot31** [doitintl/kubeip#142]
Hello !

Recently we deployed `doitintl/kubeip-agent:2.1.7` and observed all the pods are using 1 CPU each. After successfully assigning an ip to the node, the pod will keep using 1 CPU. Just to watch if the ip node has changed this seems a lot, is it normal ? (see attached screenshot)

<img width="677" alt="Capture d’écran 2024-04-04 à 09 21 23" src="https://github.com/doitintl/kubeip/assets/25128938/405e10a3-2a7c-48e0-853b-178db761f091">

**Comment by alexei-led** [comment]
@aimbot31 I'm unsure how K9s calculates CPU usage, but I think it's wrong. 
You set CPU limit to 100m (it should be enough). The KubeIP CPU usage is shallow (below 5% one core)

**Comment by alexei-led** [comment]
Fixed #144
