### ISSUE TITLE
Exposing liveness and readiness k8s probes

### ISSUE THREAD

**Issue by bygui86** [doitintl/kubeip#148]
hi everybody

KubeIP is a great tool, but it lacks one important thing: k8s probes.

What about implementing live- and readiness?

**Comment by alexei-led** [comment]
KubeIP works a daemonset and runs only once (replaces IP and does nothing till node shutdown). If K8s had a DaemonJob, I would use it instead. 
The liveness probe helps you to understand if service is up an running - not relevant for KubeIP
The readiness probe says that service is ready to accept traffic - also not relevant for KubeIP
