### ISSUE TITLE
Running as non-root

### ISSUE THREAD

**Issue by bygui86** [doitintl/kubeip#149]
hi everybody

is it possible to run KubeIP as a non-root user?

**Comment by alexei-led** [comment]
KubeIP doesn't require root user (in Docker container)
You can create your own container with KubeIP agent and run it as any user 
Can also submit a PR for the Dockerfile if you want

**Comment by bygui86** [comment]
hi @alexei-led I will try to come up with a MR with security enhancements like:
- running as non root in Dockerfile
- pod securityContext
- container securityContext

**Comment by alexei-led** [comment]
fixed with #151
