### ISSUE TITLE
Assign static IPs to existing nodes, not just newly added ones

### ISSUE THREAD

**Issue by WilliamDenniss** [doitintl/kubeIP#16]
Currently static IPs are only assigned to nodes created after the kubeIP deployment is available.

This means that if a node is added while the deployment is unavailable (e.g. it was disrupted during a node upgrade event), it won't get a static IP. It also means that any nodes existing before the deployment is available won't get static IPs assigned.

I'd suggest checking all existing nodes on boot, and at a regular interval as well, to ensure consistency.

In addition to the boot-time and unavailable kubeIP deployment cases, if you have the exact number of nodes as IPs, then during a node repair where the new node is created before the static IP is released, it won't get an assigned IP (due to none being available). If the kubeIP controller implemented the behavior to check all nodes at a regular interval, the static IP may have been freed up and could be assigned.

**Comment by avivl** [comment]
@WilliamDenniss 
`KUBEIP_FORCEASSIGNMENT` which defaults to true will check on startup and every 5 minutes if there are some nodes in the pool that are not assigned to a reserved address. If such nodes will be found then kubeip will assign a reserved address (if one is available to them)
