### ISSUE TITLE
Kubeip should update the node it is running on with care

### ISSUE THREAD

**Issue by pdecat** [doitintl/kubeip#34]
**Describe the bug**

This is a reflection I've had two weeks ago when examining the kubeip code related to updating external NAT access configs, and I've now managed to trigger the issue as described below.

When Kubeip deletes the external NAT access config with the ephemeral public IP address for the node it is running on, it looses access to the Google Compute API as it is exposed on public IP addresses.
Kubeip is then prevented to access the Google Compute API to update the `kubip_assigned` tag on nodes, or worse, create the new access config with the reserved static public IP address (more on that later).

**To Reproduce**

1. Reserve a static public IP address and tag it so kubeip will manage it
2. Create a single node GKE cluster to make sure kubeip runs on the node it will try to update
3. Install the kubeip ConfigMap and Deployment on that cluster
4. When kubeip starts, it notices the the node is not using a reserved address:
```
[kubeip-678bf66895-nkcqf] time="2018-10-03T12:21:16Z" level=info msg="kubeIP is starting" Build Date="2018-10-02-10:55" Cluster name=test-pdecat-kubeip Project name=myproject Version=b6aae34d8cdd3aba3132c04afad51c701a8fcdd9
[kubeip-678bf66895-nkcqf] time="2018-10-03T12:21:16Z" level=info msg="Starting forceAssignment" function=forceAssignment pkg=kubeip
[kubeip-678bf66895-nkcqf] time="2018-10-03T12:21:16Z" level=info msg="Starting kubeip controller" pkg=kubeip-node
[kubeip-678bf66895-nkcqf] time="2018-10-03T12:21:16Z" level=info msg="Collecting Node List..." function=processAllNodes pkg=kubeip
[kubeip-678bf66895-nkcqf] time="2018-10-03T12:21:16Z" level=info msg="kubeip controller synced and ready" pkg=kubeip-node
[kubeip-678bf66895-nkcqf] time="2018-10-03T12:21:17Z" level=info msg="Found un assigned node gke-test-pdecat-kubei-cluster1-pool-a-073827fa-s3c5" function=processAllNodes pkg=kubeip
```
5. It then proceeds with that node and locates the free reserved IP address (here 35.233.39.239):
```
[kubeip-678bf66895-nkcqf] time="2018-10-03T12:21:17Z" level=info msg="Working on gke-test-pdecat-kubei-cluster1-pool-a-073827fa-s3c5 in zone europe-west1-b" function=Kubeip pkg=kubeip
[kubeip-678bf66895-nkcqf] time="2018-10-03T12:21:17Z" level=info msg="Found node without tag gke-test-pdecat-kubei-cluster1-pool-a-073827fa-s3c5" function=assignMissingTags pkg=kubeip
[kubeip-678bf66895-nkcqf] time="2018-10-03T12:21:17Z" level=info msg="Found reserved address 35.233.39.239" function=replaceIP pkg=kubeip
```
6. When it tries to replace the node's public IP address, it hangs on the `computeService.Instances.AddAccessConfig()` call, then times out after 40 seconds
```
[kubeip-678bf66895-nkcqf] time="2018-10-03T12:21:57Z" level=error msg="AddAccessConfig \"Post https://www.googleapis.com/compute/v1/projects/myproject/zones/europe-west1-b/instances/gke-test-pdecat-kubei-cluster1-pool-a-073827fa-s3c5/addAccessConfig?alt=json&networkInterface=nic0: read tcp 10.36.0.11:49752->74.125.133.95:443: read: connection reset by peer\""
```

Notice the `connection reset by peer` error. After that the `Replaced IP for` message is never logged.

At this point, the node is left without the `kubip_assigned` tag.
In my initial reflection, I guessed it should also have been left without any public IP address, but somehow in this case, the `AddAccessConfig` call reached the Google Compute API with the old ephemeral IP address (here 35.205.240.76):

![selection_041](https://user-images.githubusercontent.com/318490/46414466-74abd080-c723-11e8-87a4-a8bdd473d970.png)

On the next kubeip ticker about 5 minutes later, a new node list collection occurred and the missing tag was added:

```
[kubeip-678bf66895-nkcqf] time="2018-10-03T12:26:16Z" level=info msg="On Ticker" function=processAllNodes pkg=kubeip
[kubeip-678bf66895-nkcqf] time="2018-10-03T12:26:16Z" level=info msg="Collecting Node List..." function=processAllNodes pkg=kubeip
[kubeip-678bf66895-nkcqf] time="2018-10-03T12:26:16Z" level=info msg="Found node without tag gke-test-pdecat-kubei-cluster1-pool-a-073827fa-s3c5" function=assignMissingTags pkg=kubeip
[kubeip-678bf66895-nkcqf] time="2018-10-03T12:26:17Z" level=info msg="Node ip is reserved 35.233.39.239" function=IsAddressReserved pkg=kubeip
[kubeip-678bf66895-nkcqf] time="2018-10-03T12:26:17Z" level=info msg="Tagging gke-test-pdecat-kubei-cluster1-pool-a-073827fa-s3c5" function=AddTagIfMissing pkg=kubeip
[kubeip-678bf66895-nkcqf] time="2018-10-03T12:26:17Z" level=info msg="Tagging node gke-test-pdecat-kubei-cluster1-pool-a-073827fa-s3c5 as 35.233.39.239" function=tagNode pkg=kubeip
```

I'm currently trying to get more detailed traces and running other tests to check if the behavior is always the same.

**Expected behavior**

Kubeip should not fail when updating the public IP address and tags of the node it is running on.

**Workaround**

I've not actually been confronted to the issue yet in production clusters but as a workaround, I've already enabled Private Google Access on the GKE cluster's subnetwork to allow an instance having only a private IP address to still access Google Compute API: https://cloud.google.com/vpc/docs/private-google-access

**Resolution**

I'm not sure yet.

Updating an access config to replace the public IP address in a `UpdateAccessConfig` Google Compute API operation [does not seem possible](https://cloud.google.com/compute/docs/ip-addresses/reserve-static-external-ip-address#IP_assign):
> An instance can have only one external IP address. If the instance already has an external IP address, you must remove that address first by deleting the old access configuration. Then, you can add a new access configuration with the new external IP address.
Last time I tried, it failed stating the `natIP` field is immutable or something like that.

Maybe [batching the delete and create operations in a single Google Compute API call](https://cloud.google.com/compute/docs/api/how-tos/batch) would be possible but I've seen no indication that the second operation would wait for the first to successfully complete and therefore succeed itself.

Other potential alternatives I've thought about:
- Update the kubeip documentation to recommend enabling Private Google Access on the GKE cluster subnetwork to workaround this issue.
- Deploy kubeip with two or more replicas and each replica would avoid altering its own node. That would require some synchronization code between the replicas to avoid races when altering nodes.
- Make kubeip [evict itself from the node it is running on](https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.10/#eviction-v1beta1-policy) to force it's migration to another node (not sure the replacement is guaranteed to be scheduled on another node and it won't work in single node cases).

**Comment by pdecat** [comment]
Here are some more test results with more detailed logs and nanosecond resolution (code at https://github.com/pdecat/kubeip/tree/8234ba226619d3b917d356a76741b5aa0a6ae0de).


# With Private Google Access disabled:

```
time="2018-10-03T16:55:11.272172478Z" level=info msg="kubeIP is starting" Build Date="2018-10-03-15:44" Cluster name=test-pdecat-kubeip Project name=myproject Version=8234ba226619d3b917d356a76741b5aa0a6ae0de
time="2018-10-03T16:55:11.277366376Z" level=info msg="Starting forceAssignment" function=forceAssignment pkg=kubeip
time="2018-10-03T16:55:11.278034426Z" level=info msg="Starting kubeip controller" pkg=kubeip-node
time="2018-10-03T16:55:11.279096626Z" level=info msg="Collecting Node List..." function=processAllNodes pkg=kubeip
time="2018-10-03T16:55:11.37830437Z" level=info msg="kubeip controller synced and ready" pkg=kubeip-node
time="2018-10-03T16:55:11.716145551Z" level=info msg="Found un assigned node gke-test-pdecat-kubei-cluster1-pool-a-073827fa-tjc9" function=processAllNodes pkg=kubeip
time="2018-10-03T16:55:11.716440622Z" level=info msg="Working on gke-test-pdecat-kubei-cluster1-pool-a-073827fa-tjc9 in zone europe-west1-b" function=Kubeip pkg=kubeip
time="2018-10-03T16:55:11.721135184Z" level=info msg="Found node without tag gke-test-pdecat-kubei-cluster1-pool-a-073827fa-tjc9" function=assignMissingTags pkg=kubeip
time="2018-10-03T16:55:12.049512096Z" level=info msg="Found reserved address 35.233.39.239" function=replaceIP pkg=kubeip
time="2018-10-03T16:55:13.129994201Z" level=info msg="Access config deletion in progress for instance gke-test-pdecat-kubei-cluster1-pool-a-073827fa-tjc9" function=replaceIP pkg=kubeip
time="2018-10-03T16:55:20.21601361Z" level=info msg="Access config deleted for instance gke-test-pdecat-kubei-cluster1-pool-a-073827fa-tjc9" function=replaceIP pkg=kubeip
time="2018-10-03T16:55:20.858648237Z" level=info msg="Access config creation in progress for instance gke-test-pdecat-kubei-cluster1-pool-a-073827fa-tjc9 with IP 35.233.39.239" function=replaceIP pkg=kubeip
time="2018-10-03T16:55:25.674663578Z" level=info msg="Replaced IP for gke-test-pdecat-kubei-cluster1-pool-a-073827fa-tjc9 zone europe-west1-b new ip 35.233.39.239" function=replaceIP pkg=kubeip
time="2018-10-03T16:55:38.884293791Z" level=error msg="Get https://10.39.240.1:443/api/v1/nodes?labelSelector=kubip_assigned%3D35-233-39-239: read tcp 10.36.1.8:60112->10.39.240.1:443: read: connection reset by peer"
time="2018-10-03T16:55:38.885531902Z" level=info msg="Tagging node gke-test-pdecat-kubei-cluster1-pool-a-073827fa-tjc9 as 35.233.39.239" function=tagNode pkg=kubeip
```

Notice that:
- the `Replaced IP for` message is here
- the one failing call is one to the kubernetes API to retrieve nodes in `GetNodeByIP` (not sure why this one failed)
- the tagging occurred

# With Private Google Access enabled:

```
time="2018-10-03T16:34:53.609959393Z" level=info msg="kubeIP is starting" Build Date="2018-10-03-15:44" Cluster name=test-pdecat-kubeip Project name=myproject Version=8234ba226619d3b917d356a76741b5aa0a6ae0de
time="2018-10-03T16:34:53.613011245Z" level=info msg="Starting forceAssignment" function=forceAssignment pkg=kubeip
time="2018-10-03T16:34:53.613162179Z" level=info msg="Starting kubeip controller" pkg=kubeip-node
time="2018-10-03T16:34:53.614397466Z" level=info msg="Collecting Node List..." function=processAllNodes pkg=kubeip
time="2018-10-03T16:34:53.713606984Z" level=info msg="kubeip controller synced and ready" pkg=kubeip-node
time="2018-10-03T16:34:54.015584784Z" level=info msg="Found un assigned node gke-test-pdecat-kubei-cluster1-pool-a-073827fa-kz0b" function=processAllNodes pkg=kubeip
time="2018-10-03T16:34:54.015811129Z" level=info msg="Working on gke-test-pdecat-kubei-cluster1-pool-a-073827fa-kz0b in zone europe-west1-b" function=Kubeip pkg=kubeip
time="2018-10-03T16:34:54.02065915Z" level=info msg="Found node without tag gke-test-pdecat-kubei-cluster1-pool-a-073827fa-kz0b" function=assignMissingTags pkg=kubeip
time="2018-10-03T16:34:54.328296892Z" level=info msg="Found reserved address 35.233.39.239" function=replaceIP pkg=kubeip
time="2018-10-03T16:34:55.509424755Z" level=info msg="Access config deletion in progress for instance gke-test-pdecat-kubei-cluster1-pool-a-073827fa-kz0b" function=replaceIP pkg=kubeip
time="2018-10-03T16:35:02.631003629Z" level=info msg="Access config deleted for instance gke-test-pdecat-kubei-cluster1-pool-a-073827fa-kz0b" function=replaceIP pkg=kubeip
time="2018-10-03T16:35:03.274858087Z" level=info msg="Access config creation in progress for instance gke-test-pdecat-kubei-cluster1-pool-a-073827fa-kz0b with IP 35.233.39.239" function=replaceIP pkg=kubeip
time="2018-10-03T16:35:05.632233883Z" level=error msg="ZoneOperations.Get \"Get https://www.googleapis.com/compute/v1/projects/myproject/zones/europe-west1-b/operations/operation-1538584502639-577559ebc9998-03ffb820-78e87e27?alt=json: read tcp 10.36.0.7:51334->108.177.15.95:443: read: connection reset by peer\" operation-1538584502639-577559ebc9998-03ffb820-78e87e27"
time="2018-10-03T16:35:05.632307834Z" level=info msg="Replaced IP for gke-test-pdecat-kubei-cluster1-pool-a-073827fa-kz0b zone europe-west1-b new ip 35.233.39.239" function=replaceIP pkg=kubeip
time="2018-10-03T16:35:18.840329311Z" level=error msg="Get https://10.39.240.1:443/api/v1/nodes?labelSelector=kubip_assigned%3D35-233-39-239: read tcp 10.36.0.7:44136->10.39.240.1:443: read: connection reset by peer"
time="2018-10-03T16:35:18.84173178Z" level=info msg="Tagging node gke-test-pdecat-kubei-cluster1-pool-a-073827fa-kz0b as 35.233.39.239" function=tagNode pkg=kubeip
```

Notice that:
- the `Replaced IP for` message is here
- the first failing call is one the Google Compute API waiting for the `AddAccessConfig` operation to complete
- the second failing call is one to the kubernetes API to retrieve nodes in `GetNodeByIP` (not sure why this one failed)
- the tagging occurred

First conclusion here is that enabling Private Google Access does not resolve the issue completely.
More testing needed...

Note: for subsequent test runs, scaling the node pool from 1 node to 0 then back to 1 is enough.

**Comment by avivl** [comment]
@pdecat Thanks for the detailed description.
If KubeIP will recover and fix the address and the TAG do you still think that this is an issue?

**Comment by pdecat** [comment]
It depends,I believe handling the errors and retrying early could improve
the situation in that nodes would not stay too long without IP address or
tag.

When/if the node is left without a public IP, it can no longer report to
the master, and when that lasts too long, it is automatically replaced with
the auto-repair feature of GKE.

In the mean time, I thought of other potential improvements :

- Start job with node anti-affinity to perform the updates (problem with
single node)
- Start Cloud function to perform the updates
- Query metadata to track access config updates instead of Compute API

Note: supporting the single node scenario is probably not a primary goal of
kubeip so it should not block the solutions

Then I came across
https://github.com/vdm/mig-static-egress-ip/blob/master/README.md which
also mentions issues without Private Google Access.

>

**Comment by avivl** [comment]
Thanks again.
I think anti-affinity is a good approch
In the coming month, I'll not have time to work on it (a lot of traveling... and other work commitments).
If you'll create a PR I'll find a time to review it.

**Comment by avivl** [comment]
@pdecat can you check if the code in https://github.com/doitintl/kubeip/tree/issue-34 solves the problem?

**Comment by pdecat** [comment]
Hi @avivl,

I've already tried that, and it failed stating the `natIP` field is immutable or something like that.

> An instance can have only one external IP address. If the instance already has an external IP address, you must remove that address first by deleting the old access configuration. Then, you can add a new access configuration with the new external IP address.

source: https://cloud.google.com/compute/docs/ip-addresses/reserve-static-external-ip-address#IP_assign

**Comment by avivl** [comment]
Thanks @pdecat 
Since KubIP is monitoring a specific node pool " KUBEIP_NODEPOO" if you install kubeip on another non monitored node-pool then we should n't have this problem. WDYT?

**Comment by pdecat** [comment]
That's indeed a workaround.

**Comment by avivl** [comment]
Ok so I'll add it to th readme file
