### ISSUE TITLE
deployment yaml Deployment object missing serviceAccountName

### ISSUE THREAD

**Issue by mmosttler** [doitintl/kubeip#35]
**Describe the bug**
After following deploy steps for using built image I was getting the following in the log:
"ERROR: logging before flag.Parse: E1019 16:31:10.936989       1 reflector.go:205] github.com/doitintl/kubeip/pkg/controller/controller.go:159: Failed to list *v1.Pod: pods is forbidden: User "system:serviceaccount:default:default" cannot list pods at the cluster scope: Unknown user "system:serviceaccount:default:default"

**To Reproduce**
1. Follow Readme docker image deploy steps.
2. Review log

**Expected behavior**
New IP assigned to node(s) in the pool.

**Screenshots**
n/a

**Desktop (please complete the following information):**
n/a

**Smartphone (please complete the following information):**
n/a

**Additional context**

**Comment by mmosttler** [comment]
After looking over the deploy/kubeip-deployment.yaml it appeared it was missing the serviceAccountName: kubeip-sa in the Deployment object.  After adding that it appears to have started up correctly and reassigned my node(s) with the new static ip.

**Comment by spark2ignite** [comment]
Thanks, @mmosttler! Would you like to submit a pull request?

**Comment by avivl** [comment]
#36
