### ISSUE TITLE
Apply arbitrary labels to nodes

### ISSUE THREAD

**Issue by wbyoung** [doitintl/kubeip#45]
Similar to #15, I'd like to have fewer static IPs than nodes. I'd like to, however have the ability to tag the node with a more customized label to allow the static IPs to serve different purposes (this is a small scale deployment at this time).

For instance:

```bash
gcloud beta compute addresses update kubeip-ip-mx0 --update-labels kubeip=$GKE_CLUSTER_NAME,kubeip-node-labels=mx:second-label

gcloud beta compute addresses update kubeip-ip-web0 --update-labels kubeip=$GKE_CLUSTER_NAME,kubeip-node-labels=web
```

Would this be something that fits in the scope of this project? Would it be hard to add? I can take a stab when I have time if you can point me in the right direction.

**Comment by avivl** [comment]
@wbyoung this shouldn't be too hard to add. I don't have the bandwidth for it now.
You can take a look [here](https://github.com/doitintl/kubeip/blob/master/pkg/kipcompute/compute.go#L198) and make the replacment based on any rules

**Comment by avivl** [comment]
@wbyoung Can you please explain what exactly do you need? You can apply any labels to your cluster.
What the expected behavior from Kubeip?

**Comment by wbyoung** [comment]
@avivl, I was thinking of the following use case for a single cluster:

- Accept incoming mail
- Accept incoming web traffic

In this case, it'd be useful to be able to have two pools of static IPs (with the appropriate DNS records) and to have the nodes run the corresponding services, right?

The labels would allow defining rules for which nodes the services would run on.

Is there another way one would handle this?

**Comment by wbyoung** [comment]
I think #49 may be a different feature from the request here, but looks useful.

If #49 does solve the above use case, can you give an example of how to configure things to handle the previous comment (which is for a single node pool)?

**Comment by avivl** [comment]
@eranchetz can you explain(You'll probably do a better job than me)

**Comment by eranchetz** [comment]
Hey @wbyoung, 

I'll give a simplified example, I hope it will make sense. 
I have 2 node pools with 1 instance each: 
- pool-web
- pool-mx

I reserve 2 static ips and label them:
`kubeip-node-pool=pool-web`
`kubeip-node-pool=pool-web`

The result will be that pool-web will only use the web static ip address
and `pool-mx` will only use the mx static ip. 

now, all we have to do is use `nodeSelector` for the web/mx deployment
deployment-web will run on the pool-web

Let us know if this makes sense for you.

**Comment by wbyoung** [comment]
@eranchetz and is there a way to get it working with a single node pool? That was part of my request & the above discussion.

**Comment by eranchetz** [comment]
Not really, I also think this is not good practice, since a node-pool instance is ephemeral, tagging a specific node (especially in cloud environments) might create a situation in which your static ip is not attached to the correct service. 
I think that having a logical group (in this case a node-pool) is the "cheapest" most reliable option.

**Comment by wbyoung** [comment]
The point would be to allow the service (pod) to be assigned to the proper node based on the label. That responsibility applied to the developer and/or cluster admin, right?

If tags are assigned when the static IPs are assigned and nodes that have static IPs don't have them removed (I'm assuming this is how this project works), then I'm not sure how this would be unsafe.

The ephemeral nature of nodes doesn't really seem like it changes much here. Labels just allow rules for how to schedule pods regardless of the lifetime of a node. If a node dies or is removed, the freed static IP becomes available. Pods running on the node will be restarted (and may not be scheduable based on label based constraints). A new node may or may not be created to replace this node. The static IP that is now free will be assigned to a node if possible. The same tag that went with the node before will be assigned when the IP is assigned. It's possible that the scheduler will now be able to schedule pods that were previously unscheduable. There's nothing odd going on here that the ephemeral nature of nodes interferes with. Can you give a more complete example to the contrary?
