### ISSUE TITLE
Documentation fix - configure nodeSelector before deploying

### ISSUE THREAD

**Issue by talonx** [doitintl/kubeip#67]
**Describe the bug**
The documentation does not mention that the kubeip deployment YAML has a nodeSelector (for itself) - "cloud.google.com/gke-nodepool: pool-kubip". This needs to be either edited before deployment to match the node labels on which it will be deployed, or the label needs to be added to the node(s). 
Doing it without this step would result in a deployment failure.

**To Reproduce**
1. README.md does not have any mention of the nodeSelector

**Expected behavior**
kubeip to get deployed

**Screenshots**
NA

**Desktop (please complete the following information):**
NA

**Smartphone (please complete the following information):**
NA

**Additional context**

**Comment by avivl** [comment]
#68
