### ISSUE TITLE
Feature Request: kubeip helm chart

### ISSUE THREAD

**Issue by rd-michel** [doitintl/kubeip#81]
**Is your feature request related to a problem? Please describe.**
instead of people creating their own way to automate the installation of kubeip ... please provide a helm chart.

**Describe the solution you'd like**
Fast and easy way to deploy kubeip to my environment via helm chart.

**Comment by alexei-led** [comment]
KubeIP v2 is deployed as DaemonSet, the YAML is pretty simple and needs to configure target nodes with `nodeSelector` or `affinity`. I see no reason to create Helm chart for this.
