### ISSUE TITLE
Addresses for newly created nodes update on ticker, not on creation

### ISSUE THREAD

**Issue by shachar-fastsimon** [doitintl/kubeip#88]
**Describe the bug**
When a new node is created, it is not updated until the "On ticker" check runs.
There is a "Did not found node pool" error when the node is created though, so the "created" event does reach the controller, it just fails for some reason.

**To Reproduce**
1. Create a new node in the KUBEIP_NODEPOOL node pool

**Expected behavior**
The node IP address should immediately update.

**Screenshots**
![image](https://user-images.githubusercontent.com/101321954/185795934-319fb2d0-16e5-46ce-802e-2f5750489e5e.png)
The node was created at 14:01 and only updated at 14:08 on the ticker.
(The ticker was set to 10 minutes here for test, normally it's 1 minute.)

**Comment by alexei-led** [comment]
Fixed with KubeIP v2 (deployed as Daemonset)
