### ISSUE TITLE
Feature Request: export prom style metrics about what kubeip is doing.

### ISSUE THREAD

**Issue by DanTulovsky** [doitintl/kubeip#89]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
Feature Request: export prom style metrics about what kubeip is doing in order to monitor it for errors.

**Describe alternatives you've considered**

**Additional context**

**Comment by aushafy** [comment]
what we need to expose ? So far for my case, I think we can export which IP address that pointed to what node VM name

**Comment by alexei-led** [comment]
no plans to implement this for KubeIP v1.
KubeIP v2 can use log-based metrics for this case (together with `--json` flag or `LOG_JSON` env)
